AWSTemplateFormatVersion: '2010-09-09'
Description: NYC Taxi Data Lake S3 Bucket

Parameters:
  DataLakeBucketName:
    Type: String
    Description: Name of the S3 data lake bucket

Resources:
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataLakeBucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  DataLakeBucketName:
    Description: Data lake bucket name
    Value: !Ref DataLakeBucket
